name = "kv-orm-cf-workers-example"
type = "webpack"
private = false
account_id = "5a883b414d4090a1442b20361f3c43a9"

[[kv-namespaces]]
binding = "KVORMCFWORKERSEXAMPLE"
id = "0ab8c19f30c94e8dbebd62a280bd2d4a"
